// ⚠️ AUTO-GENERATED BY GESTORAY MODULE INSTALLER CLI - DO NOT TOUCH DIRECTLY!
import type { MenuItemConfig } from '$lib/stores/menu';

export const MODULE_MENU_SNIPPETS: MenuItemConfig[] = [  

  { id: 'products', label: 'Gestione Prodotti', icon: 'Package', path: '/dashboard/products', rolesView: ['superadmin', 'direzione'] },
];
