// ⚠️ AUTO-GENERATED BY GESTORAY MODULE INSTALLER CLI - DO NOT TOUCH DIRECTLY!
export const MODULE_FEATURE_SNIPPETS: Record<string, any> = {  

  products: { id: 'products', label: 'Catalogo Prodotti', description: 'Listini e catalogo articoli', enabled: true, moduleKey: 'products' },
};
