// ⚠️ AUTO-GENERATED BY GESTORAY MODULE INSTALLER CLI - DO NOT TOUCH DIRECTLY!
import type { MenuItemConfig } from '$lib/stores/menu';

export const MODULE_MENU_SNIPPETS: MenuItemConfig[] = [  { id: 'activities', label: 'Gestione Attività', icon: 'ClipboardList', path: '/dashboard/activities', rolesView: ['superadmin', 'direzione', 'commerciale', 'amministrazione'] },
  { id: 'products', label: 'Gestione Prodotti', icon: 'Package', path: '/dashboard/products', rolesView: ['superadmin', 'direzione'] },
];
