// ⚠️ AUTO-GENERATED BY GESTORAY MODULE INSTALLER CLI - DO NOT TOUCH DIRECTLY!
export const MODULE_ROLES_SNIPPETS: any[] = [  {
  module: 'activities',
  label: 'Attività & Task',
  actions: [
    { key: 'list', label: 'Elenco' },
    { key: 'read', label: 'Dettaglio' },
    { key: 'create', label: 'Creazione' },
    { key: 'update', label: 'Modifica' },
    { key: 'delete', label: 'Eliminazione' },
  ]
},
  {
  module: 'products',
  label: 'Catalogo Prodotti',
  actions: [
    { key: 'list', label: 'Elenco' },
    { key: 'read', label: 'Dettaglio' },
    { key: 'create', label: 'Creazione' },
    { key: 'update', label: 'Modifica' },
    { key: 'delete', label: 'Eliminazione' },
  ]
},
];
